---
- name: Copy Logstash configuration.
  template:
    src: logstash.yml.j2
    dest: "/etc/logstash/logstash.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash

- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-beats-input.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash

- name: Create Logstash filters.
  copy:
    src: "filters/{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-syslog.conf
    - 11-nginx.conf
    - 12-apache.conf
    - 15-drupal.conf
    - 16-mutate.conf
  notify: restart logstash

- name: Create Logstash configuration file for local syslog.
  template:
    src: 02-local-syslog-input.conf.j2
    dest: /etc/logstash/conf.d/02-local-syslog-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_local_syslog
  notify: restart logstash

- name: Ensure configuration for local syslog is absent if disabled.
  file:
    path: /etc/logstash/conf.d/02-local-syslog-input.conf
    state: absent
  when: not logstash_monitor_local_syslog
  notify: restart logstash

- name: update JVM options
  lineinfile:
    dest: /etc/logstash/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^-Xms(.*)$', line: '-Xms{{ logstash_jvm_heap_size_gb }}g' }
    - { regexp: '-Xmx(.*)$', line: '-Xmx{{ logstash_jvm_heap_size_gb }}g' }
  notify: restart logstash
